website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from .models import Post, User, Comment, Like
from . import db
from sqlalchemy import desc

views = Blueprint("views", __name__)

@views.route("/", methods=['GET'], defaults={"page": 1}) 
@views.route("/home", methods=['GET'], defaults={"page": 1})
@views.route('/home/<int:page>',methods=['GET'])
def home(page):
    page=page
    per_page = 10
    posts = db.session.query(Post).order_by(desc(Post.like_num)).paginate(page,per_page,error_out=False)


    return render_template("home.html", user = current_user, posts=posts)


@views.route("/create-post", methods = ['GET','POST'])
@login_required
def create_post():
    if request.method == "POST":
        title = request.form['title']
        content = request.form['content']
        if not title:
            flash('Title cannot be empty!', category='error')
        elif not content:
            flash('Topic cannot be empty!', category='error')
        else:
            post = Post(title=title, content=content, author = current_user.id)
            db.session.add(post)
            db.session.commit()
            flash('New topic created!', category = 'success')
            return redirect(url_for('views.home'))

    return render_template('create_post.html', user=current_user)

@views.route("/delete-post/<id>")
@login_required
def delete_post(id):
    post = Post.query.filter_by(id=id).first()

    if not post:
        flash('Post does not exist', category='error')
    elif current_user.id != post.author:
        flash('You do not have permission to delete this post', category='error')
    else:
        db.session.delete(post)
        db.session.commit()
        flash('Successfully deleted!', category='success')

    
    return redirect(url_for('views.home'))

@views.route("/posts/<username>",methods=['GET'], defaults={"page": 1})
@views.route("/posts/<username>/<int:page>",methods=['GET'])
@login_required
def posts(username, page):
    user = User.query.filter_by(username=username).first()
    page=page
    per_page = 4
    if not user:
        flash('No user with that username exists.', category='error')
        return redirect(url_for('views.home'))

    posts = Post.query.filter_by(author=user.id).order_by(desc(Post.date_created)).paginate(page,per_page,error_out=False)

    return render_template("posts.html", user=current_user, posts=posts, username=username)


@views.route("/edit-post/<id>", methods=['GET','POST'])
@login_required
def edit_post(id):
    post = Post.query.filter_by(id=id).first()
    if request.method == "POST":
        post.title = request.form['title']
        post.content = request.form['content']
        if not post.title:
            flash('Title is required!', category='error')
        elif not post.content:
            flash('Content is required!', category='error')
        else:   
            post.update=Post(title=post.title,content=post.content,author = current_user.id)
            db.session.add(post)
            db.session.commit()
            flash('Topic has been updated!', category='success')
            return redirect(url_for('views.home'))

    return render_template('edit_post.html', user=current_user)

@views.route("/create-comment/<post_id>", methods=['POST'])
@login_required
def create_comment(post_id):
    text = request.form.get('text')

    if not text:
        flash('Comment cannot be empty!', category='error')
    else:
        post = Post.query.filter_by(id=post_id)
        if post:
            comment = Comment(
                text=text, author=current_user.id, post_id=post_id)
            db.session.add(comment)
            db.session.commit()
        else:
            flash('Post does not exist.', category='error')

    return redirect(url_for('views.home'))


@views.route("/delete-comment/<comment_id>")
@login_required
def delete_comment(comment_id):
    comment = Comment.query.filter_by(id=comment_id).first()

    if not comment:
        flash('Comment does not exist.', category='error')
    elif current_user.id != comment.author and current_user.id != comment.post.author:
        flash('You do not have permission to delete this comment.', category='error')
    else:
        db.session.delete(comment)
        db.session.commit()

    return redirect(url_for('views.home'))
    
@views.route("/like-post/<post_id>", methods=['GET'])
@login_required
def like(post_id):
    post = Post.query.filter_by(id=post_id).first()
    like = Like.query.filter_by(
        author=current_user.id, post_id=post_id).first()

    if not post:
        flash('Topic does not exist!', category='error')
    elif like:
        post.like_num = post.like_num - 1
        db.session.delete(like)
        db.session.commit()
    else:
        like = Like(author=current_user.id, post_id=post_id)
        post.like_num = post.like_num + 1
        db.session.add(like)
        db.session.commit()

    return redirect(url_for('views.home'))

website/templates/admin.html
{% extends "posts_div.html" %} {% block title %}Admin{% endblock %} 
{% block content
    %}
    <form method="POST">
    <div class="position-relative"></div>
    <div class="position-absolute top-50 start-50 translate-middle">
      <h3 align="center">Enter a password for administrators</h3>
      <br />
      <div class="form-group">
        
        <input
          type="password"
          id="password"
          name="password"
          class="form-control"
          placeholder="Enter Password"
        />
        <br />
        <div align="center">
          <button class="btn" style="background-color: #9786c9; color:aliceblue" type="submit">Enter</button>
        </div>
    </div>
</div>
{%endblock%}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
  
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <script
      src="https://kit.fontawesome.com/999ca2bb93.js"
      crossorigin="anonymous"
    ></script>

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg" style="background-color: #9786c9;">
      <div class="container-fluid">
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbar"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="/home" style="color:aliceblue">Home</a>
            {% if user.is_authenticated %}
          
            <a class="nav-item nav-link" href="/logout" style="color:aliceblue">Logout</a>
            <a class="nav-item nav-link" href="/create-post" style="color:aliceblue">Create a Topic</a>
            {% else %}
            <a class="nav-item nav-link" href="/login" style="color:aliceblue">Login</a>
            <a class="nav-item nav-link" href="/sign-up" style="color:aliceblue">Sign Up</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}
    <div class="container">{% block content %}{% endblock %}</div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
    <script
    type="text/javascript"
    src="{{ url_for('static', filename='index.js')}}"
  ></script>
   
  </body>
</html>

website/templates/create_post.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
    %}

    <div class="mx-auto" style="margin-top: 30px;">

    <h1 align="center" style="color:#9786c9">Create a Topic</h1>
    
    <form method="POST">
      
      
        <input type="text" name="title"
               placeholder="Title"
               style="width: 100%;
               padding: 10px 15px;
               margin: 5px 0;
               box-sizing: border-box;"
               value="{{ request.form['title'] }}"></input>
      
        <textarea name="content"
                  placeholder="Topic content"
                  style="width: 100%;
               padding: 10px 15px;
               margin: 5px 0;
               box-sizing: border-box;"
                  
                  >{{ request.form['content'] }}</textarea>
      
      
        <div align="center">
          <button type="submit" style = "background-color:#9786c9; color:aliceblue" class="btn btn-lg">Post</button>
        </div>
    </form>
    <br />
    <div align="center">
      <a href="/home"
        ><button type="button" class="btn btn-sm btn-secondary">Back</button></a
      >
    </div>
</div>
    {% endblock %}

website/templates/edit_post.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
    %}

    <div class="mx-auto" style="margin-top: 30px;">

    <h1 align="center" style="color:#9786c9">Edit a Topic</h1>
    
    <form method="POST">
      <br>
      <input type="text" name="title"
             placeholder="Title"
             style="width: 100%;
               padding: 10px 15px;
               margin: 5px 0;
               box-sizing: border-box;"
             value="{{ request.form['title'] }}"></input>
      <br>
      <textarea name="content"
                placeholder="Message content"
                style="width: 100%;
               padding: 10px 15px;
               margin: 5px 0;
               box-sizing: border-box;"
                >{{ request.form['content'] }}</textarea>
      <br>
      <br />
      <div align="center">
        <button type="submit" class="btn btn-lg" style="background-color:#9786c9; color:aliceblue">Edit</button>
      </div>
    </form>
    <br />
    <div align="center">
      <a href="/home"
        ><button type="button" class="btn btn-sm btn-secondary">Back</button></a
      >
    </div>
</div>
    {% endblock %}

website/templates/home.html
{% extends "posts_div.html" %} {% block title %}Home{% endblock %} 

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
    %}
    <form method="POST">
    <div class="position-relative"></div>
    <div class="position-absolute top-50 start-50 translate-middle">
      <h3 align="center">Login</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="text"
          id="email"
          name="email"
          class="form-control"
          placeholder="Enter Email"
        />
        <label for="password">Password</label>
        <input
          type="password"
          id="password"
          name="password"
          class="form-control"
          placeholder="Enter Password"
        />
        <br />
        <div align="center">
          <button class="btn" style="background-color: #9786c9; color:aliceblue" type="submit">Login</button>
        </div>
        </div>
        <br />
        <div align="center">
        <a href="/home" style="color:#9786c9">I'm a guest</a>
      </div>
      <br />
      <div align="center">
        <a href="/admin-enter" style="color:#9786c9">I'm an administrator</a>
      </div>
      </div>
     
    </div>

    </form>
    {% endblock %}

website/templates/posts.html
{% extends "posts_div.html" %} {% block title %}{{username}}'s Posts{% endblock
    %}
    {%block header%} <h1 align="left" style = color:#9786c9> {{username}}'s topics: </h1>{%endblock%}
   {%block footer%}
    <div align="center">
      
        {% if posts.has_prev %}<a style="color:#9786c9" href="{{ url_for('views.posts', page=posts.prev_num, username=current_user.username) }}">&lt;&lt; Previous page</a>{% else %}&lt;&lt; Previous page{% endif %} | 
        {% if posts.has_next %}<a style="color:#9786c9" href="{{ url_for('views.posts',page=posts.next_num,username=current_user.username) }}">Next page &gt;&gt;</a>{% else %}Next page &gt;&gt;{% endif %}
       
      
    </div>
{%endblock%}

website/templates/posts_div.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content%}
<meta charset="UTF-8">
<div class="mx-auto" style="margin-top: 30px;">
<h1 align="center" style="color:#9786c9">{%block header%}Hot Topics &#128293;     
{%endblock%}</h1> 
<div id="posts">
  {% for post in posts.items %}
  <div class="card border-dark">
    <div class="card-header d-flex justify-content-between align-items-center">
      <a style ="color:#9786c9" href="/posts/{{post.user.username}}">{{post.user.username}}</a>
      <div>
        
        {{ post.likes|length }}
        {% if user.id in post.likes|map(attribute="author")|list %}
        <a href="/like-post/{{post.id}}"><i style = "color:#9786c9" class = "fas fa-thumbs-up"></i></a>
        {% else %}
        <a href="/like-post/{{post.id}}"><i style = "color:#9786c9" class = "far fa-thumbs-up"></i></a>
        {% endif %} {% if user.id == post.author %}
        <div class="btn-group">
          <button
            type="button"
            style="color:#9786c9"
            class="btn btn-sm dropdown-toggle"
            data-bs-toggle="dropdown"
          ></button>
          <ul class="dropdown-menu">
            <li>
              <a href="/delete-post/{{post.id}}" class="dropdown-item"
                >Delete</a
              >
              <a href="/edit-post/{{post.id}}" class="dropdown-item"
              >Edit</a
            >
            </li>
          </ul>
        </div>
        {% endif %}
      </div>
    </div>
    <div class="card-body">
      <div class="card-title" align="center" style="font-size:135%">{{post.title}}</div>
      <div class="card-text">{{post.content}}</div>
      <br />
      <div class="collapse" id="comments-{{post.id}}">
        <div class="card">
          <div class="card-body" id="comments-expanded-{{post.id}}">
            {% for comment in post.comments %}
            <div class="d-flex justify-content-between align-items-center">
              <div>
                <a style="color:#9786c9" href="/posts/{{comment.user.username}}"
                  >{{comment.user.username}}</a
                >: {{comment.text}}
              </div>
              <div>
                <small class="text-muted"> {{comment.date_created}}</small>
                {% if user.id == comment.author or user.id == post.author %}
                <div class="btn-group">
                  <button
                    type="button"
                    class="btn btn-sm dropdown-toggle"
                    style="color:#9786c9"
                    data-bs-toggle="dropdown"
                  ></button>
                  <ul class="dropdown-menu">
                    <li>
                      <a
                        
                        href="/delete-comment/{{comment.id}}"
                        class="dropdown-item"
                        >Delete</a
                      >
                    </li>
                  </ul>
                </div>
                {% endif %}
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
      <p class="card-text">
        {% if post.comments|length > 1 %}
        <a style="color:#9786c9" data-bs-toggle="collapse" href="#comments-{{post.id}}" role="button">
          <small>View {{post.comments|length}} Comments</small>
        </a>
        {% elif post.comments|length == 1 %}
        <a style="color:#9786c9"  data-bs-toggle="collapse" href="#comments-{{post.id}}" role="button">
          <small>View {{post.comments|length}} Comment</small>
        </a>
        {% else %}
        <small class="text-muted">No Comments</small>
        {% endif %}
      </p>
      <form
        class="input-group mb-3"
        method="POST"
        action="/create-comment/{{post.id}}"
      >
        <input
          type="text"
          id="text"
          name="text"
          class="form-control"
          placeholder="Comment something!"
        />
        <button type="submit" style="background-color:#9786c9; color:aliceblue" class="btn">Comment</button>
      </form>
    </div>
    <div class="card-footer text-muted">{{post.date_created}}</div>
  </div>
  <br/ > {% endfor %}
</div>
{% block footer %}
<div align="center">
{% if posts.has_prev %}<a style="color:#9786c9" href="{{ url_for('views.home', page=posts.prev_num) }}">&lt;&lt; Previous page</a>{% else %}&lt;&lt; Previous page{% endif %} | 
{% if posts.has_next %}<a style="color:#9786c9" href="{{ url_for('views.home', page=posts.next_num) }}">Next page &gt;&gt;</a>{% else %}Next page &gt;&gt;{% endif %}
</div>
{% endblock %}
{%endblock%} 

website/templates/signup.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
    content %}
    <form method="POST">
        <div class="position-relative"></div>
    <div class="position-absolute top-50 start-50 translate-middle">
      <h3 align="center">Sign Up</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="text"
          id="email"
          name="email"
          class="form-control"
          placeholder="Enter Email"
        />
        <label for="username">Username</label>
        <input
          type="text"
          id="username"
          name="username"
          class="form-control"
          placeholder="Enter Username"
        />
        <label for="password1">Password</label>
        <input
          type="password"
          id="password1"
          name="password1"
          class="form-control"
          placeholder="Enter Password"
        />
        <label for="password2">Password Again</label>
        <input
          type="password"
          id="password2"
          name="password2"
          class="form-control"
          placeholder="Enter Password Again"
        />
        <br />
        <div align="center">
          <button class="btn" style="background-color: #9786c9; color:aliceblue" type="submit">Sign Up</button>
        </div>
    </div>
</div>
      </div>
    </form>
    {% endblock %}